### ISSUE TITLE
More Maps

### ISSUE THREAD

**Issue by Sodak** [Garrus2142/Slashers#10]
The Map Part is kinda easy... U just need to get via console the getpos of the entity u want to place or just gmapper to place ur entity/model and get the coordinates for the sv_randomplacer.lua   and for the killer just use the player spawns for terrorist and counter-terrorists if u create a map.. Steinman could make an easy tutorial for setting up the spawns in the hammer editor. But its allowed to create a custom map?

**Comment by Guilhem-Pech** [comment]
Steinman is already  writting a mapping tutorial

**Comment by Steinman** [comment]
As Daryl said I'm writing a mapping tutorial that will be completed with a tool made by Daryl, it should be out very soon. We're also working on 2 official maps right now
