### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by Sodak** [Garrus2142/Slashers#17]
Just for the Dev Build If u add more Classes you can play with more than 20 Players.. But the Scoreboard dont look that good.. but thats not my suggestion.

Make it for Admins so.. If u open scoreboard and rightclick u get ur cursor  and if u click on a Name u open the steamprofile webpage or just a dropdownmenu with possiblities to kick him or ban... (using ulx)

**Comment by Guilhem-Pech** [comment]
- This gamemode is not conceived to handle more than 10 players (even dev branch) and it'll nerver be
- Thank you for your suggestion but this is not the right place to do that ^^, use github for issues only (or if you're a dev, propose some updates ^^). However we will think about it !

**Comment by Sodak** [comment]
Yeah but for the 10 player handle it also possible to design the scoreboard   with the rightclick part... the 20 player part i can just edit it to display the scoreboard to left to right to fill out the screen

**Comment by Guilhem-Pech** [comment]
Yeah like I said we'll think about it

**Comment by Sodak** [comment]
Another Question in the Randomplacer.lua is the spawning of jerrycan and so...  but i want to make a function to spawn ammo for the stungun on the highschool map but if i add the ammo it only spawns one and not more.. how possible can i add a player.GetAll  math random u know what i mean? just for the table Ammo{
