### ISSUE TITLE
Why doesn't this map work

### ISSUE THREAD

**Issue by MoistSeni** [Garrus2142/Slashers#23]
Each time I load the map it says "Your map differs from the server's".
If someone can tell me or link me the solution to this problem that'll just be fantastic.
P.S. The map looks good and I REALLY wanna play it

**Comment by Sodak** [comment]
Which Map?

**Comment by MoistSeni** [comment]
Summer Camp.

**Comment by Sodak** [comment]
Maybe the server is using an old file from workshop... is it just an error on one server or on more?

**Comment by MoistSeni** [comment]
It's happening on all of them.

**Comment by Sodak** [comment]
maybe clear ur cache folder and download folder where all gmas is and desubscribe to all slasher addons and redownload and join again of the server

**Comment by MoistSeni** [comment]
How do I clear the cache folder? Where is the cache folder?

**Comment by Sodak** [comment]
C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\cache   here is cache

C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\downloads\server

here downloaded gmas from servers

**Comment by MoistSeni** [comment]
thx

**Comment by Guilhem-Pech** [comment]
I assume it's fixed
