### ISSUE TITLE
Question for a Friend.

### ISSUE THREAD

**Issue by Sodak** [Garrus2142/Slashers#24]
https://steamcommunity.com/id/jakobb71/myworkshopfiles/?p=2  Maybe Steinman could communicate with king pommes to edit his maps :D

A friend of mine is modifiying ure gamemode for his server and he wants to ask if u want some code hes adding this features:

`
20 new classes for 20 players to play

Flaregun added for Rob

German translation added

Trent has a baseball bat to push the killer away and slow down

Eric has a bow that stuns the killer for 2 seconds and makes him unable to move

Adam activates the generator fastest

ESC menu added

Names over the head of the players Red = Killer, Blue = Survivor. Visible only from a certain distance

Voice Radius added. The Living Players can speak in a radius of 500 SE

DeadTalk - The dead can no longer speak to the living.

Shotgun and Tommy Jarvis.`

**Comment by ghost** [comment]
hey m8 i added my version now u mustnt ask
