### ISSUE TITLE
Dev Branch:

### ISSUE THREAD

**Issue by Sodak** [Garrus2142/Slashers#32]
using F2 in Waiting Players and if i vote and another is on server he gets an error:

[ERROR] gamemodes/slashers/gamemode/modules/votemap/cl_votemap.lua:170: attempt to index upvalue 'backVote' (a nil value)

Guess we have to deactivate the F2 Key and just allow end of map vote instead of votemap by f2    RTV u can add fast...   just copy the changemap function and remove the if gm config values

**Comment by Guilhem-Pech** [comment]
I've pushed an update can you tell me if it's fixed ?

**Comment by Sodak** [comment]
I will look into it but looks good

**Comment by Guilhem-Pech** [comment]
Fixed
