### ISSUE TITLE
Votemap. 

### ISSUE THREAD

**Issue by Niwaki** [Garrus2142/Slashers#35]
I have this error:  
[ERROR] gamemodes/slashers/gamemode/modules/votemap/cl_votemap.lua:149: attempt to index upvalue 'backVote' (a nil value)
  1. func - gamemodes/slashers/gamemode/modules/votemap/cl_votemap.lua:149
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by Guilhem-Pech** [comment]
I posted a fix

**Comment by Niwaki** [comment]
It's cool!
