### ISSUE TITLE
SV_Choosekiller @Garrus

### ISSUE THREAD

**Issue by ghost** [Garrus2142/Slashers#37]
Hey Garrus I have a Question:

How does the sv_choosekiller work..

I understand that every player will start with 100 Points to get selected as killer. If someone is a Killer and the Survivors Win he get 10 Points from the GM.CONFIG["round_choosekiller_add"].  So it means that he cannot be a killer in this gameround anymore but on the nextmap.. when the txt files get resettet or new writed with 100 points is it right?  Or can u explain it like it work to me?

I want to do something with the points... if the point number is higher ure more able to get the killer... so if u found a jerrycan u get 1 point for the choosekiller.... just as idea but i need to understand the function...

thanks alot.

**Comment by Garrus2142** [comment]
The file is persistent, never reset unless you remove it. At each round if a player has more points than other, he become killer. When players has same points, its random. The points is added at all survivors regardless they win or not.

**Comment by ghost** [comment]
Thanks now i unterstand :)
