### ISSUE TITLE
Lots of problems with the new update.

### ISSUE THREAD

**Issue by Niwaki** [Garrus2142/Slashers#38]
I don't know, but the whole mode just breaks down because of the new update I think the problem with var mod to fix it.

**Comment by ghost** [comment]
The new dev version works fine. I tested it.. did u changed the Sv randomplacer lua? Because there u just remove the map data. I will look for it anyway.

**Comment by ghost** [comment]
And what does not work now?  the gamemode itself or just some functions?

**Comment by Guilhem-Pech** [comment]
Keep in mind that this is the dev branch so it's unstable

**Comment by Guilhem-Pech** [comment]
But what errors do you have  are you using a modified version or only this one ?

**Comment by ghost** [comment]
Maybe he forget to change the sv_randomplacement.lua  to change... because i forget it, too yesterday or today at 2AM :D  but on my server it works...

**Comment by Niwaki** [comment]
[ERROR] gamemodes/slashers/gamemode/core/rounds/sv_rounds.lua:277: attempt to compare nil with number
  1. fn - gamemodes/slashers/gamemode/core/rounds/sv_rounds.lua:277
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by Niwaki** [comment]
Add this to config.lua
GM.CONFIG["round_count_nextmap"] = 5

**Comment by Niwaki** [comment]
CreateConVar("slashers_round_max", 5, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_ARCHIVE, FCVAR_REPLICATED}, "Max round before change map.")
use ConVar this

**Comment by ghost** [comment]
Ah yeah the new convar options... i did not add them cuz i like the way the config does more... than server.cfg cvars......    

I will look into it.

**Comment by Niwaki** [comment]
You will fix these problems?

**Comment by ghost** [comment]
I will look into it on my local machine and try to fix.. i guess garrus forget one file to change using the convar...

**Comment by Niwaki** [comment]
The next problem that I noticed is the problem with the lack of players on the server, there is always written /3, although I changed the value to 2

**Comment by Niwaki** [comment]
And with a choice of language

**Comment by ghost** [comment]
Yeah its caused by the convars.. im not using it.. and it works... so

**Comment by Niwaki** [comment]
In short as I understand it the problem is that almost no where is it written convar?

**Comment by Niwaki** [comment]
Can you give us a link to the profile?

**Comment by ghost** [comment]
U mean from garrus?

**Comment by Niwaki** [comment]
No

**Comment by Guilhem-Pech** [comment]
If you use a modified version please dont ask here we don't provide solutions for them. 
Go in private but not  here.

**Comment by Niwaki** [comment]
I'm just saying that you've fixed
