### ISSUE TITLE
Killing Floor 2 and L4D2 Melee Weapons.

### ISSUE THREAD

**Issue by ghost** [Garrus2142/Slashers#39]
Hey maybe u can add some melee weapons from the tfa bases mentioned in the title.

They got nice ClientSide Animations in First Person (not in third person)  rly cool swing animations.

U just had to copy the tfa_gun_base  and tfa_bash_base from the reduxed pack and the tfa_melee_base   gun and bash rename to tfa_gun_base 2  and tfa_bash_base2  after that ure just adding the modules from tfa:  att and tfa_enum      to the modules folder from gamemode... afterwars u just have to add some more tfa_modules  and remove some unneccessary hook files...  but i know vyn is working on a own weapon base.  Just take a look

**Comment by Guilhem-Pech** [comment]
@LPDaVinci please wait the update and then we'll see if it's good or not

**Comment by ghost** [comment]
Yeah i wait for ur new base vyn is coding...  but tfa just bring animations withit and he can saves time daryl daryl.

and till i test the new weapons there was no error.. but i will look onto it... but now i have to work..

**Comment by Sodak** [comment]
LPDA just stop posting here these guys are just french... u know what kinda of person they are.
