### ISSUE TITLE
character description stuck on screen

### ISSUE THREAD

**Issue by homonovus** [Garrus2142/Slashers#4]
right after spawning, pressing f1 to view the character's description will cause the spawn message to stay on screen

**Comment by homonovus** [comment]
seems to be only fixed by a reconnect

**Comment by Guilhem-Pech** [comment]
There is a close buttom at the left corner of the menu

**Comment by homonovus** [comment]
the description from when you spawn persists, not the one you open

**Comment by Sodak** [comment]
Just use the F1 button to make a toggleing of the screen it opens via a function called after spawn just use the f1 key to if window is opened if u press f1 the opened window get closed.. just make a if statement for this

**Comment by Garrus2142** [comment]
Fixed in next update
