### ISSUE TITLE
A couple of bugs that you need to fix

### ISSUE THREAD

**Issue by KurimuzonAkuma** [Garrus2142/Slashers#53]
1. If you hit any object with a weapon, then it flies incredibly far (people or any object) bind for attack "bind alt +zoom" (I fixed it on my server, lel)
2. On the map "slash_motel" Bates can put his mother pretty quickly and see if there are players nearby (Could you add a cooldown?)
3. No icons for maps (https://imgur.com/a/rw9H5wR)
4. In sv_class.lua file add 1 line of code self:SetHealth because when only setMaxHealth survivors have only 100hp independently of configuration (https://imgur.com/a/rmi5NtF)
5. Another bugs on slash_motel (https://imgur.com/a/ekI3JgB)
6. On slash_selvage survivors can jump on this roof, but the killer does not (https://imgur.com/a/yLqXNnV) P.S. I don't know what's wrong with pumpkins, I think it's my fault :D
7. Russian translate not correctly, use this: (https://pastebin.com/Nsefi9K0)

**Comment by Guilhem-Pech** [comment]
Thank you for your report we will see what we can do about it
