### ISSUE TITLE
Spawning Issues

### ISSUE THREAD

**Issue by Wheatley126** [Garrus2142/Slashers#7]
I've had multiple errors upon spawning in where It shows a Derpy Face Sydney on the character picture, then I have tons of lua errors saying...

[Utopia Games - Slashers gamemode] gamemodes/slashers/gamemode/modules/f1menu/cl_f1menu.lua:52: attempt to concatenate upvalue 'CharacName' (a nil value)
  1. OnEnd - gamemodes/slashers/gamemode/modules/f1menu/cl_f1menu.lua:52
   2. unknown - lua/includes/extensions/client/panel/animation.lua:48

and my game is extremely laggy to the point where I have to reconnect

There's also been times where the killer spawns with no weapon, however, I've noticed that 'The Intruder' will still have his traps, so I think it has something to with weapon randomization.

**Comment by Garrus2142** [comment]
This error is fixed in next update
