### ISSUE TITLE
Missing textures and errors

### ISSUE THREAD

**Issue by Allgrunfan50** [Garrus2142/Slashers#8]
For some reasons, the picture that shows who you are, keys, stamina bar and some killer icons are missing textures
2 killers are errors for me: The subway killer and the Lodge killer, along with his beartraps
The emo character is an error for me aswell, how do i fix this?

**Comment by Wheatley126** [comment]
I'm not a developer, but it might be because you didn't restart the game after installing the addon

**Comment by homonovus** [comment]
you dont need to subscribe to the addon to get the textures, just have the server set up correctly and make sure that **your** settings allow for materials to be downloaded

**Comment by Steinman** [comment]
Just restart your game and/or uninstall then reinstall the content packs, this is a Workshop issue
