### ISSUE TITLE
Add DeadTalk and Livin Talk and Spectate Mode

### ISSUE THREAD

**Issue by Sodak** [Garrus2142/Slashers#9]
Simple in the Title:

Can you add some hooks that u cannot talk to the living while ure dead and maybe a spectate mode for AFK People where there get switched to spectator.

And Pls add the Flaregun today i saw a server added the flaregun into his gamemode.
It slows down the killer and start to ignite him while hes slowed.

**Comment by homonovus** [comment]
the igniting of the killer is purely cosmetic, i'm sure
the revolver already stuns the killer

**Comment by Sodak** [comment]
Yeah the revolver stuns, i saw the nmrih flaregun if u shoot the flare pops out if u hit the killer he gets ignite and slowed if u hit a survivor nothing will happen. just a nice weapon for use. because we need more weapons now i work on the compund bow to make a slow too

**Comment by Guilhem-Pech** [comment]
This is not Friday 13th

**Comment by Sodak** [comment]
I try to use this code.. idk if this work:

`function PlayerCanHearPlayersVoice( ply, rec )
		if ( !ply:Alive() ) and ( !rec:Alive() ) then -- If they are both dead they can hear each other.
		return true
	elseif ( ply:Alive() ) and ( rec:Alive() ) and ( rec:GetPos():Distance( ply:GetPos() ) < 500 ) then	-- If they are both alive and is the distance under 500 they can hear each other.
		return true
	else -- If they are not either both alive or dead then they can't hear each other.
		return false
	end



end
hook.Add( "PlayerCanHearPlayersVoice", "PlayerStartedTheirVoiceChat", PlayerCanHearPlayersVoice)`


this hook has to been run serverside...

i cannot test if it works

**Comment by Sodak** [comment]
OK WORKS... ADD this into the game and deactive sv_alltalk 0  on the server
